vektorprogrammet/vektorprogrammet

composer.lock
Added composer.lock to make composer easier
=> Added composer.lock to make composer easier

app/Resources/views/base.html.twig
Removed "vektorprogrammet" in contactinfo and linkedin
=> Small fix in frontpage

app/Resources/views/Survey/survey_results.html.twig, app/Resources/views/admission/index.html.twig, app/Resources/views/admission_admin/layout.html.twig, app/Resources/views/article/index.html.twig, app/Resources/views/article_admin/form.html.twig, app/Resources/views/article_admin/index.html.twig, app/Resources/views/gallery/gallery.html.twig, app/Resources/views/home/index.html.twig, app/Resources/views/interview/conduct.html.twig, app/Resources/views/interview/schedule.html.twig, app/Resources/views/interview/schema.html.twig, app/Resources/views/interview/schemas.html.twig, app/Resources/views/interview/show.html.twig, app/Resources/views/login/login.html.twig, app/Resources/views/participant_history/index.html.twig, app/Resources/views/profile/edit_profile.html.twig, app/Resources/views/profile/edit_profile_admin.html.twig, app/Resources/views/profile/edit_profile_password.html.twig, app/Resources/views/profile/edit_profile_photo.html.twig, app/Resources/views/profile/profile.html.twig, app/Resources/views/profile/public_profile.html.twig, app/Resources/views/reset_password/reset_password.html.twig, app/Resources/views/school_admin/all_users.html.twig, app/Resources/views/school_admin/create_school.html.twig, app/Resources/views/sponsors/sponsors_edit.html.twig, app/Resources/views/statistics/statistics.html.twig, app/Resources/views/substitute/edit.html.twig, app/Resources/views/substitute/index.html.twig
Fixed a bunch of missing titles
=> Fixed a bunch of missing titles

app/Resources/views/base.html.twig
Fixed social media links in topNav.
Changed link to LinkedIn with Instagram in topNav
=> Fixed links in topNav

app/config/routing.yml, src/AppBundle/Controller/AdmissionAdminController.php
New users created from admission page are now added with username and password
=> New users are created with Username and Password

app/Resources/views/admission_admin/layout.html.twig, src/AppBundle/Controller/AdmissionAdminController.php, src/AppBundle/Entity/Repository/SemesterRepository.php
Display the department name, semester name and total number of applicants on the admissionAdmin page.
The twig template was styled so the new info would fit in both the admin view and super admin view.
Should the inline styling be moved to a css file?
=> Department name, semester name and # of applicants

app/Resources/views/admission/index.html.twig, src/AppBundle/Twig/Extension/StaticContentExtension.php
CKeditor now makes new record for requested HTML id that does not exist.
Admission page have now possibility for different description
=> CKeditor fix og individuelle statiske tekster

src/AppBundle/Entity/User.php
Changed default picture path to "images/defaultProfile.jpg"
=> Changed default picture path to "images/defaultProfile.jpg"

app/Resources/views/profile/profile.html.twig, app/Resources/views/profile/public_profile.html.twig, src/AppBundle/Entity/WorkHistory.php
Added default message to profile if no start- and/or  end semester is chosen
=> Added default start/end semester message on profile

src/AppBundle/Entity/Repository/WorkHistoryRepository.php
fikset doctrine funksjoner knyttet til arbeidshistorikk som følge av semester-endringene
=> WorkHistoryRepsitory Fix

app/config/config.yml
Tillate pdf filer ved opplasting når en skriver artikler
=> uploadFileTypeFix

app/Resources/views/school_admin/index.html.twig, app/Resources/views/semester_admin/index.html.twig, app/Resources/views/team_admin/index.html.twig, src/AppBundle/Controller/SchoolAdminController.php, src/AppBundle/Controller/SemesterController.php, src/AppBundle/Controller/TeamAdminController.php
Vise avdeling på semester admin, team admin og skoleadmin
=> viewDepartNameInAdminViews

app/Resources/views/about/board_and_team.html.twig
Fikset litt på profilvisning (Epost og link til profil) i Styre og team side.
=> Fikset litt på profilvisning (Epost og link til profil) i Styre og team side.

app/Resources/views/about/board_and_team.html.twig
All profile divs are left-aligned
=> All profile divs are left-aligned

app/Resources/views/survey/survey_create.html.twig
=> fixed optional alternatives for new questions

src/AppBundle/Controller/SchoolAdminController.php
Gjør det mulig å tildele skole til "Uaktive" brukere. (siden ingen assistenter er aktive dette semesteret)
=> tilfelSkoleMidlertidigFix

app/Resources/views/base.html.twig
Fikset slik at 404 siden faktisk kan vises i prod
(security er ikke lastet ved 404, og vi kan derfor ikke sjekke hvilken rolle brukeren har)
=> Fixed 404 page

app/Resources/views/survey/takeSurvey.html.twig, src/AppBundle/Controller/SurveyController.php, src/AppBundle/Entity/Survey.php, src/AppBundle/Entity/SurveyAnswer.php, src/AppBundle/Entity/SurveySchoolAnswered.php, src/AppBundle/Entity/SurveyTaken.php, src/AppBundle/Form/Type/SurveyExecuteType.php
Binder svarene sammen med en 'schoolAnswered' slik at vi kan se alle svarene en person har svart på en undersøkelse. Da kan vi finne statistikk som 'Hvor mange i 8.klasse fikk hjelp av vektorassistentene?'.
=> Ryddet opp survey-kode for å følge Best Practice

app/Resources/views/survey/survey_result.html.twig, src/AppBundle/Controller/ApplicationStatisticsController.php, src/AppBundle/Controller/SurveyController.php, src/AppBundle/Entity/Repository/SurveyTakenRepository.php
Laget resultatsider for undersøkelser.
Viser hvilke skoler som har svart på undersøkelsen, og hvor mange som har svart.
=> Google charts på alle resultater med tall

app/Resources/views/survey/takeSurvey.html.twig
Fjerne 'Send inn' når knappen trykkes på
=> Fjerne 'Send inn' når knappen trykkes på

app/Resources/views/survey/survey_result.html.twig, src/AppBundle/Controller/SurveyController.php
Vi burde fjerne duplikate svar i databasen før vi pusher den her til master
=> textResultater

src/AppBundle/Entity/SurveyAnswer.php
!!! Viktig !!!
Byttet answer type fra 'varchar'(maks 255 characters) til 'longtext'(maks 4,294,967,295 charactes)
=> Answer type Varchar -> LongText

src/AppBundle/Entity/SurveyAnswer.php
Alle surveyTaken sine surveyAnswers blir slettet når surveyTaken slettes
=> Slette surveyAnswers

src/AppBundle/Controller/SemesterController.php, src/AppBundle/Entity/Semester.php, src/AppBundle/Form/Type/CreateSemesterType.php
Nytt semester får navn fra dropdownliste med år + radio button med høst/vår
=> Nytt semester får navn fra dropdownliste med år + radio button med høst/vår

app/Resources/views/participant_history/index.html.twig, src/AppBundle/Controller/ParticipantHistoryController.php
Har laget en ny liste under deltakerhistorie med aktive assistenter. Har også lagt til antall personer i alle listene
=> Antall assistenter dette semesteret

app/Resources/views/admission_admin/assigned_applications_table.html.twig, app/Resources/views/admission_admin/layout.html.twig, app/Resources/views/admission_admin/new_applications_table.html.twig, src/AppBundle/Controller/AdmissionAdminController.php
Se hvor mange hver person skal intervjue i tabell øverst.
Se alle personene du skal intervjue i tabell.
Kan styles mye bedre om noen har lyst til det :)
=> Opptak; liste over dine intervjuer + intervjufordeling

app/Resources/views/article/show.html.twig, app/Resources/views/base.html.twig
Byttet til 'imageSmall'.
Ryddet opp i description
=> Facebook v2

app/Resources/views/base.html.twig
Force 404 twig to be rendered in the ExceptionController
=> Force 404 twig to be rendered

app/Resources/views/article_admin/form.html.twig, app/Resources/views/base.html.twig
Problemet er at filbrowseren ikke vil gi path til det som er over article_images. Dette burde egentlig vært løst med å gi rett path fra filbrowser, men nå har jeg løst det ved å endre src til bildeobjektene til artikkelen som blir endret. Funker vertfall ved ny artikkel.
=> articleImageFix

app/Resources/views/base.html.twig
Lagt inn tag for farge i header til mobil nettlesere
=> Lagt inn tag for farge i header til mobil nettlesere

app/Resources/FMElfinderBundle/views/Elfinder/ckeditor.html.twig, app/Resources/FMElfinderBundle/views/Elfinder/elfinder_type.html.twig, app/Resources/views/article_admin/form.html.twig
Fiks i twig fil til ckeditor og elfinder! Tatt bort fix fra artikkeladmin
=> ElFinder Fiks

src/AppBundle/Controller/SchoolAdminController.php
ikke-superadmins kan se inaktivebrukere ved tildeling av skoler
=> ikke-superadmins kan se inaktivebrukere ved tildeling av skoler

app/Resources/views/admission_admin/create_application.html.twig, app/Resources/views/admission_admin/new_applications_table.html.twig, app/config/routing.yml, app/config/security.yml, src/AppBundle/Controller/AdmissionAdminController.php, src/AppBundle/Entity/Repository/SemesterRepository.php
Registrere søkere manuelt for dette semesteret under kontrollpanel>opptak>Ny søker
=> etterRegistrering

app/Resources/views/profile/edit_profile_photo.html.twig, app/Resources/views/profile/profile.html.twig, app/Resources/views/profile/public_profile.html.twig, app/config/routing.yml, src/AppBundle/Controller/ProfileController.php
Super admins can edit profile photos
=> Super admins can edit profile photos

app/Resources/views/admission_admin/interviewed_applications_table.html.twig, app/Resources/views/admission_admin/new_applications_table.html.twig
Fixed bulk actions on sorted table
=> Fixed bulk actions on sorted table

app/Resources/views/admission/index.html.twig
=> Ny tekst på opptakssiden

app/Resources/views/new_user/create_new_user_email.txt.twig, app/config/routing.yml, src/AppBundle/Controller/UserAdminController.php
Updated email text.
Moved code for user activation form.
admissionAdminController needs cleanup
=> Activate New Users

src/AppBundle/Controller/SurveyController.php
Undersøkelser krever kun admin-rettigheter
=> Undersøkelser krever kun admin-rettigheter

app/Resources/views/school_admin/index.html.twig, src/AppBundle/Entity/School.php, src/AppBundle/Form/Type/CreateSchoolType.php
Skoler kan nå velges til å være internasjonale
=> Skoler kan nå velges til å være internasjonale

app/Resources/views/base.html.twig, app/Resources/views/members/members.html.twig, app/config/routing.yml, app/config/security.yml, src/AppBundle/Controller/MembersController.php, src/AppBundle/Entity/Repository/AssistantHistoryRepository.php
Ny visningsside for alle assistenter
=> Ny assistentside 

src/AppBundle/Controller/AdmissionAdminController.php, src/AppBundle/Controller/InterviewController.php, src/AppBundle/DataFixtures/ORM/LoadApplicationData.php, src/AppBundle/DataFixtures/ORM/LoadUserData.php, src/AppBundle/Entity/Repository/AdmissionRepository.php, src/AppBundle/Tests/Controller/AdmissionAdminControllerTest.php, src/AppBundle/Tests/Controller/InterviewControllerTest.php
Kun superadmins og brukeren som var intervjuer har tilgang til å lese intervjuet
=> Hide Interviews

app/Resources/assets/scss/app.scss, app/Resources/views/admission_admin/assigned_applications_table.html.twig, app/Resources/views/admission_admin/assigned_table.html.twig, app/Resources/views/admission_admin/layout.html.twig, app/Resources/views/interview/conduct.html.twig, app/config/routing.yml, src/AppBundle/Controller/AdmissionAdminController.php, src/AppBundle/Controller/InterviewController.php, src/AppBundle/DataFixtures/ORM/LoadApplicationData.php, src/AppBundle/DataFixtures/ORM/LoadUserData.php, src/AppBundle/Entity/Interview.php, src/AppBundle/Entity/Repository/ApplicationRepository.php, src/AppBundle/Tests/Controller/AdmissionAdminControllerTest.php, src/AppBundle/Tests/Controller/InterviewControllerTest.php
På intervjuene finnes det nå en knapp, 'ikke møtt', som kansellerer intervjuet,
findAssignedApplicants() og findNewApplicants() returnerer nå kun Applications som ikke er kansellert.
=> Kansellere intervjuer

app/Resources/assets/scss/app.scss, app/Resources/views/control_panel/index.html.twig, app/Resources/views/control_panel/sbs.html.twig, src/AppBundle/Controller/ControlPanelController.php, src/AppBundle/Entity/Repository/SemesterRepository.php
Fullstendig Step-by-step komponent
=> Step-by-step

app/config/config_prod.yml
Send error log to webansvarlig@vektorprogrammet.no when an internal server error occurs (500 error)
=> Send 500 errors to webansvarlig@vektorprogrammet.no

app/Resources/assets/js/app.js, app/Resources/assets/scss/app.scss, app/Resources/views/survey/survey_result.html.twig, app/config/routing.yml, src/AppBundle/Controller/SurveyController.php, src/AppBundle/Entity/Survey.php, src/AppBundle/Entity/SurveyAnswer.php, src/AppBundle/Entity/SurveyQuestion.php, src/AppBundle/Entity/SurveyQuestionAlternative.php, src/AppBundle/Entity/SurveyTaken.php
Pie charts + funksjon for å filtrere svar.
=> Ny resultatside for undersøkelser

app/Resources/views/survey/survey_result.html.twig
Synes det ble litt for mye rødt i pie chartene. Endret rekkefølgen
fra:
Rød -> Grønn -> Blå -> Gul -> Lilla
til:
Blå -> Grønn -> Lilla -> Gul -> Rød
Er dette bedre?
=> Change color order on pie charts

src/AppBundle/Entity/Repository/WorkHistoryRepository.php, src/AppBundle/Tests/Controller/TeamAdminControllerTest.php
Brukere i team som har sluttsemester med sluttdato i fremtiden vil lenger ikke vises i alle teamene.
=> Fix bug in findWorkHistoriesByTeam

app/config/routing.yml, src/AppBundle/Controller/AdmissionController.php, src/AppBundle/Entity/Repository/DepartmentRepository.php
Attention! Please look over the code - it includes accepting user input, and I haven't used symfony before.
/avdeling/{short_name} = /opptak/avdeling/{id}
routing.yml:
- Added route for /avdeling/{short_name}
AdmissionController:
- basic logic for determining whether {id} or {short_name} is provided
DepartmentRepository.php:
- Created query for search of lower case short_names $em->Repo->findDepartmentByShortName()
TODO:
- Handle department not found
@ Line 42, DepartmentRepository: Function intended to return one (first) result. Just wanted to make you aware of this. Maybe you want this to be handled by caller?
=> Added permalink alias:

app/Resources/views/admission_admin/existing_assistants_applications_table.html.twig, app/Resources/views/admission_admin/interviewed_applications_table.html.twig, app/Resources/views/admission_admin/new_applications_table.html.twig
Gruppe handling - Gruppehandling
=> Ord delings feil:

src/AppBundle/Form/Type/CreateTeamType.php
=> Endre label Beskrivelse -> Lang beskrivelse

app/Resources/views/team/team_page.html.twig
=> Email on team page

app/Resources/views/team/team_page.html.twig
=> Team title created

app/Resources/views/team_admin/create_team.html.twig, src/AppBundle/Entity/Team.php, src/AppBundle/Form/Type/CreateTeamType.php
=> Updated characters left in shortDescription

app/Resources/views/team_admin/create_team.html.twig, src/AppBundle/Controller/AdmissionAdminController.php, src/AppBundle/Controller/CertificateController.php, src/AppBundle/Controller/InterviewController.php, src/AppBundle/Controller/ProfileController.php, src/AppBundle/Controller/SchoolAdminController.php, src/AppBundle/Controller/SponsorsController.php, src/AppBundle/Controller/StaticContentController.php, src/AppBundle/Controller/SurveyResultsController.php, src/AppBundle/Controller/TeamAdminController.php, src/AppBundle/Entity/Team.php, src/AppBundle/Form/Type/CreateTeamType.php, src/AppBundle/Form/Type/InterviewQuestionType.php, src/AppBundle/Form/Type/SurveyQuestionType.php
Issue #270 #261 #263 #264 #265 #266 #267 #268 #269 #271 #273 #272 #274 #275 #276
=> Commented code

app/Resources/views/admission_admin/new_applications_table.html.twig, src/AppBundle/Controller/AdmissionAdminController.php
Set user to application if user already exists
=> Fix admin admission after admission end date

app/Resources/assets/scss/app.scss, app/Resources/views/adminBase.html.twig, app/Resources/views/control_panel/index.html.twig, app/Resources/views/field_of_study/form.html.twig, app/Resources/views/field_of_study/show_all.html.twig, app/config/routing.yml, app/config/security.yml, src/AppBundle/Controller/FieldOfStudyController.php, src/AppBundle/Entity/Repository/FieldOfStudyRepository.php, src/AppBundle/Form/FieldOfStudyType.php
=> CRU functionality for field of study

app/Resources/views/team/team_page.html.twig
=> Facebook team share

app/Resources/views/form/surv_layout.html.twig, app/Resources/views/survey/takeSurvey.html.twig
=> Create survey form layout

src/AppBundle/Controller/ArticleController.php, src/AppBundle/Entity/Repository/AssistantHistoryRepository.php, src/AppBundle/Entity/Repository/UserRepository.php, src/AppBundle/Form/Type/ApplicationType.php, src/AppBundle/Form/Type/SponsorType.php, src/AppBundle/Form/Type/SurveyExecuteType.php
Fix #292, #291, #290, #289, #288 and #287
=> Cleanup unused 'use' statements

app/Resources/views/control_panel/sbs.html.twig, app/Resources/views/statistics/statistics.html.twig, src/AppBundle/Controller/ApplicationStatisticsController.php, src/AppBundle/Controller/ControlPanelController.php, src/AppBundle/Entity/Repository/AssistantHistoryRepository.php
Added counters for total assistantpositions in SBS and admission statistics
=> assistantPositions

app/Resources/views/sponsors/sponsors.html.twig, app/Resources/views/team/application_email.html.twig, src/AppBundle/DataFixtures/ORM/LoadSponsorData.php, src/AppBundle/Entity/TeamApplication.php, src/AppBundle/Twig/Extension/SponsorsExtension.php
Hovedsponsor vises ikke når det ikke finnes hovedsponsor. 
Nå sendes epost med riktig informasjon ved teamsøknad.
=> Logo fix & team application email

app/Resources/views/newsletter/show_letters.html.twig
Fixed table on show sent letters
=> Newsletter fixed table letters

app/Resources/assets/scss/app.scss, app/Resources/views/sponsors/sponsors.html.twig
Logos will now display properly on smaller screens
=> Fixed logo view for smaller screens

app/Resources/assets/js/allocation.js, app/Resources/assets/scss/partials/_typography.scss, app/Resources/views/school_admin/school_allocate_main.html.twig, app/Resources/views/school_admin/school_allocate_show.html.twig, src/AppBundle/Controller/SchoolAllocationController.php, src/AppBundle/DataFixtures/ORM/LoadDepartmentData.php, src/AppBundle/DataFixtures/ORM/LoadSchoolCapacityData.php, src/AppBundle/DataFixtures/ORM/LoadSchoolData.php
Har flyttet mye av koden inn i to klasser; `Assistant` og `School`.
Laget funksjoner for:
- å sjekke om skolene har plass til flere assistenter
- oppdatere skole-dropdown når dag eller bolk endres
- synkronisere ledige skoler i dropdown-lister til alle assistenter
=> Synchronize day, group and school select lists

app/Resources/assets/js/genericAjax.js, src/AppBundle/Service/ApplicationData.php
=> Fix activate/deactivate user

app/Resources/assets/scss/app.scss, app/Resources/views/admission/index.html.twig, src/AppBundle/Controller/AdmissionController.php, src/AppBundle/DataFixtures/ORM/LoadTeamData.php, src/AppBundle/Entity/Repository/TeamRepository.php
Bedre synlighet for opptak til team i søknadsperioden. Nå vises hvilke team som har opptak på fremsiden til opptaket
=> Team opptak

src/AppBundle/Controller/AdmissionAdminController.php, src/AppBundle/Controller/AssistantHistoryController.php, src/AppBundle/Controller/InterviewController.php, src/AppBundle/Controller/UserAdminController.php, src/AppBundle/Form/Type/CreateUserType.php, src/AppBundle/Role/Roles.php, src/AppBundle/Service/InterviewManager.php, src/AppBundle/Service/RoleManager.php, src/AppBundle/Service/UserRegistration.php
`const ASSISTANT = 'ROLE_USER';`
`const TEAM_MEMBER = 'ROLE_ADMIN';`
`const TEAM_LEADER = 'ROLE_SUPER_ADMIN';`
`const ADMIN = 'ROLE_HIGHEST_ADMIN';`
=> Move user role constants to Roles class

app/Resources/views/admission_admin/interviewed_applications_table.html.twig
Vis telefonnummer for ferdige intervjuer slik at skolekoordinering for en enklere jobb!
=> Telfonnummer for intervjuede assistenter

src/AppBundle/Entity/Signature.php
=> Validate signature form

src/AppBundle/Entity/Application.php, src/AppBundle/Entity/AssistantHistory.php, src/AppBundle/Entity/Letter.php, src/AppBundle/Entity/Newsletter.php, src/AppBundle/Entity/SchoolCapacity.php, src/AppBundle/Entity/Semester.php, src/AppBundle/Entity/Sponsor.php, src/AppBundle/Entity/Subscriber.php, src/AppBundle/Entity/Survey.php, src/AppBundle/Entity/SurveyAnswer.php, src/AppBundle/Entity/SurveyQuestion.php, src/AppBundle/Entity/SurveyTaken.php, src/AppBundle/Entity/Team.php, src/AppBundle/Entity/TeamApplication.php
=> Fix mixed return and parameter types in entities

app/Resources/views/team/receipt.html.twig, app/Resources/views/team/team_application.html.twig, src/AppBundle/Controller/TeamApplicationController.php, src/AppBundle/Entity/TeamApplication.php, src/AppBundle/Event/TeamApplicationCreatedEvent.php, src/AppBundle/EventSubscriber/TeamApplicationSubscriber.php, src/AppBundle/Resources/config/services.yml
Flyttet kode for å sende email fra `TeamApplicationController` til en EventSubscriber, `TeamApplicationSubscriber`. Dispatcher en `TeamApplicationEvent` fra controlleren som blir fanget opp av subscriberen, som så kjører funksjonene sine. Har også lagt til logging og notification til Slack i subscriberen.
=> Refactor team application action. Add logging

src/AppBundle/Command/UpdateUserRolesCommand.php, src/AppBundle/DataFixtures/ORM/LoadUserData.php, src/AppBundle/DataFixtures/ORM/LoadWorkHistoryData.php, src/AppBundle/Entity/User.php, src/AppBundle/Entity/WorkHistory.php, src/AppBundle/Tests/Command/UpdateUserRolesCommandTest.php
Assistant users that are in teams will be promoted to Team members.
Users NOT in team will be demoted to Assistants.
=> Create console command to update user roles

app/Resources/views/team_admin/index.html.twig, src/AppBundle/Controller/TeamAdminController.php, src/AppBundle/Entity/Repository/TeamRepository.php
Ingen department har så mange teams at vi trenger å søke etter riktig team. Sorterer heller listen med teams.
=> Remove team search box

app/Resources/views/common/flash.html.twig, app/Resources/views/team_admin/specific_team.html.twig, src/AppBundle/Controller/TeamAdminController.php, src/AppBundle/Entity/WorkHistory.php, src/AppBundle/Event/WorkHistoryCreatedEvent.php, src/AppBundle/EventSubscriber/WorkHistorySubscriber.php, src/AppBundle/Resources/config/services.yml
=> Promote users to team member when added to team

src/AppBundle/Tests/Controller/AboutVektorControllerTest.php
Reverts vektorprogrammet/vektorprogrammet#500
=> Revert "Use BaseWebTestCase in AboutVektorControllerTest"

app/Resources/views/base/mobile_navigation.html.twig
=> FAQ visible in mobile navigation

app/Resources/views/survey/takeSurvey.html.twig
=> Semester info i undersøkelser

app/Resources/views/admission_admin/assigned_table.html.twig, app/Resources/views/interview/email.html.twig, app/Resources/views/interview/schedule.html.twig, src/AppBundle/Controller/InterviewController.php, src/AppBundle/Entity/Interview.php, src/AppBundle/Form/Type/ScheduleInterviewType.php, src/AppBundle/Service/InterviewManager.php
Reverts vektorprogrammet/vektorprogrammet#495
=> Revert "Interview mail room"

app/Resources/views/base/admin/main_navigation.html.twig, app/Resources/views/base/admin/mobile_navigation.html.twig, app/Resources/views/executive_board/index.html.twig, app/Resources/views/survey/surveys.html.twig
Issue #530, #518 og endret link på medlemmer i hovedstyret
=> Email list dropdown menu

app/Resources/views/base/admin/main_navigation.html.twig, app/Resources/views/base/admin/mobile_navigation.html.twig, app/Resources/views/control_panel/index.html.twig
=> Vikarlink -> Opptak & undersøkelse

app/Resources/views/control_panel/step_by_step/steps/step4.html.twig
=> SBS: link til opptaksstatistikk i 'Fordel'

app/Resources/views/control_panel/index.html.twig, app/Resources/views/user_admin/create_user.html.twig, app/config/security.yml, src/AppBundle/Controller/UserAdminController.php
=> Only teamleaders can create new members to other departments

src/AppBundle/Controller/ExecutiveBoardController.php
=> Preview executive board after update - fix

app/Resources/views/article_admin/form.html.twig, app/Resources/views/interview/show.html.twig, app/Resources/views/substitute/index.html.twig
This error also made the menu button unresponsive on mobile.
#537
=> Fixed modernizr console error for affected pages.

.gitignore, composer.json, composer.lock, src/AppBundle/Controller/AdmissionAdminController.php, src/AppBundle/Controller/TeamApplicationController.php, src/AppBundle/EventSubscriber/SupportTicketSubscriber.php
Husk å kjøre `npm run setup`
Php codestyle fixer (`npm run cs`) har blitt ~1000% - 4500% raskere hos meg på windows (!!!)
=> Update php fixer and other dependencies

src/AppBundle/Entity/Subscriber.php
=> Validate name and email for subscribers

package.json
=> Fix setup script

src/AppBundle/DataFixtures/ORM/LoadSemesterData.php
=> Fix semester fixtures

app/Resources/views/team_admin/work_history_table.html.twig
=> Only admins can see the delete button on team members

app/Resources/views/interview/preview.html.twig, app/Resources/views/interview/schedule.html.twig, app/config/routing.yml, src/AppBundle/Controller/InterviewController.php, src/AppBundle/Form/Type/ScheduleInterviewType.php
=> Inteview mail preview

app/Resources/views/team_admin/index.html.twig
=> Show email and acceptApplication in team list in CP

src/AppBundle/EventSubscriber/ReceiptSubscriber.php, src/AppBundle/Resources/config/services.yml
So for example:
Receipt *15e5333b242* edited. -> Receipt *15e5333b242* belonging to Assistent Johansen was edited by Admin Johansen.
=> Receipt log

app/DoctrineMigrations/Version20170927171228.php, app/Resources/assets/scss/app.scss, app/Resources/views/survey/finish_page.html.twig, app/Resources/views/survey/survey_create.html.twig, src/AppBundle/Controller/SurveyController.php, src/AppBundle/Entity/Survey.php, src/AppBundle/Form/Type/SurveyType.php
=> Custom survey finish page

src/AppBundle/AssistantScheduling/Assistant.php, src/AppBundle/AssistantScheduling/Webapp/src/App.vue, src/AppBundle/AssistantScheduling/Webapp/src/Schedule.js, src/AppBundle/Controller/AssistantSchedulingController.php
=> Add email to schedule csv export

src/AppBundle/EventSubscriber/WorkHistorySubscriber.php
To prevent conflict with company email maker
=> Increase role_update priority in WH events

app/Resources/views/survey/survey_result.html.twig, app/Resources/views/survey/takeSurvey.html.twig, src/AppBundle/Controller/SurveyController.php, src/AppBundle/Entity/Survey.php, src/AppBundle/Entity/SurveyAnswer.php, src/AppBundle/Entity/SurveyTaken.php, src/AppBundle/Form/Type/SurveyAnswerType.php, src/AppBundle/Form/Type/SurveyQuestionType.php
=> Add checkboxes to Survey

src/AppBundle/Entity/TeamApplication.php
=> Limit fieldOfStudy (TeamApplication) to 45 characters

app/Resources/views/receipt_admin/receipts_table_individual.html.twig
=> Show receipt status for team members

app/DoctrineMigrations/Version20171031162242.php, app/Resources/views/survey/survey_create.html.twig, app/Resources/views/survey/surveys.html.twig, src/AppBundle/Entity/Survey.php, src/AppBundle/Form/Type/SurveyType.php
Fixes #686 
Nå kan undersøkelser skjules for teammedlemmer
=> Survey confidentiality

src/AppBundle/Event/CrudEvent.php, src/AppBundle/Event/ReceiptEvent.php, src/AppBundle/Event/TeamEvent.php, src/AppBundle/Event/UserEvent.php, src/AppBundle/EventSubscriber/CrudLogger.php, src/AppBundle/EventSubscriber/ExceptionSubscriber.php, src/AppBundle/EventSubscriber/ReceiptSubscriber.php, src/AppBundle/EventSubscriber/UserSubscriber.php, src/AppBundle/Resources/config/services.yml
Automatically apply basic CREATE, UPDATE and DELETE logging to events implementing the `CrudLogger` interface
=> CRUD logger

app/Resources/views/admission/existingUser.html.twig, app/Resources/views/interview/conduct.html.twig, src/AppBundle/Form/Type/ApplicationExistingUserType.php, src/AppBundle/Form/Type/ApplicationPracticalType.php, src/AppBundle/Tests/Controller/AdmissionControllerTest.php
=> Add year of study to interview form

app/DoctrineMigrations/Version20180120131625.php, app/Resources/assets/scss/app.scss, app/Resources/views/admission_admin/interviewed_applications_table.html.twig, app/Resources/views/interview/conduct.html.twig, app/Resources/views/interview/show.html.twig, src/AppBundle/Entity/Application.php, src/AppBundle/Form/Type/ApplicationInterviewType.php
=> Add special needs to interview form

app/DoctrineMigrations/Version20180125142315.php, app/Resources/views/interview/request_new_time.html.twig, app/Resources/views/interview/reschedule_email.html.twig, app/Resources/views/interview/response.html.twig, app/config/routing.yml, src/AppBundle/Controller/InterviewController.php, src/AppBundle/Entity/Interview.php, src/AppBundle/Form/InterviewNewTimeType.php, src/AppBundle/Tests/Controller/AdmissionAdminControllerTest.php
Fixes #622 
De som blir innkalt til intervju kan spesifisere hvilke tidspunkt som ikke passer når de ber om nytt intervju.
Meldingen blir sendt på epost til intervjuansvarlig.
=> New interview textfield

app/Resources/views/survey/survey_result.html.twig, src/AppBundle/Controller/SurveyController.php, src/AppBundle/Entity/Survey.php
Fixes #681 
Har gjort så skolenavnet vises sammen med tekstsvaret i en undersøkelse.
=> Showing school name when showing text answers

app/Resources/views/admission/existingUser.html.twig, app/Resources/views/admission/index.html.twig, app/Resources/views/common/flash.html.twig, src/AppBundle/Controller/AdmissionController.php, src/AppBundle/Entity/Repository/ApplicationRepository.php, src/AppBundle/EventSubscriber/ApplicationSubscriber.php, src/AppBundle/EventSubscriber/SupportTicketSubscriber.php, src/AppBundle/Service/ApplicationData.php
=> Display error if submitting application with duplicate email

app/Resources/views/interview/show.html.twig, src/AppBundle/Entity/InterviewAnswer.php, src/AppBundle/Form/Type/InterviewAnswerType.php, src/AppBundle/Service/InterviewManager.php, src/AppBundle/Tests/Controller/InterviewControllerTest.php, src/AppBundle/Validator/Constraints/InterviewAnswer.php, src/AppBundle/Validator/Constraints/InterviewAnswerValidator.php
=> Un-require checkbox questions in interviews

app/Resources/views/team/team_page.html.twig
=> Changed email in styre og team to vektor email

app/Resources/views/admission_admin/assigned_applications/all_interviews_table.html.twig, app/Resources/views/admission_admin/assigned_applications/cancelled_interviews_table.html.twig, app/Resources/views/admission_admin/assigned_applications/interview_distribution.html.twig, app/Resources/views/admission_admin/assigned_applications/logged_in_user_interview_table.html.twig, app/Resources/views/admission_admin/assigned_applications_table.html.twig, app/Resources/views/admission_admin/assigned_table.html.twig, app/Resources/views/admission_admin/existing_assistants_applications_table.html.twig, app/Resources/views/admission_admin/layout.html.twig, app/Resources/views/substitute/index.html.twig
=> Fix interview tables not sorting (issue #740 and #745)

app/Resources/assets/scss/app.scss, app/Resources/views/admission_admin/assigned_applications/all_interviews_table.html.twig, app/Resources/views/admission_admin/assigned_applications/cancelled_interviews_table.html.twig, app/Resources/views/admission_admin/assigned_applications/interview_distribution.html.twig, app/Resources/views/admission_admin/assigned_applications/logged_in_user_interview_table.html.twig, app/Resources/views/admission_admin/assigned_applications_table.html.twig, app/Resources/views/admission_admin/assigned_table.html.twig, app/Resources/views/admission_admin/existing_assistants_applications_table.html.twig, app/Resources/views/admission_admin/interviewed_applications_table.html.twig, app/Resources/views/admission_admin/layout.html.twig, app/Resources/views/admission_admin/new_applications/table.html.twig, app/Resources/views/admission_admin/teamInterest.html.twig, app/Resources/views/substitute/index.html.twig
=> Sorting tables

app/Resources/assets/scss/app.scss, app/Resources/views/newsletter/show_all_newsletters.html.twig, app/Resources/views/team/team_application.html.twig, app/config/routing.yml, app/config/security.yml, src/AppBundle/Tests/Controller/AdmissionControllerTest.php, src/AppBundle/Tests/Controller/NewsletterControllerTest.php
=> Newsletter issue#593

app/Resources/views/admission/existingUser.html.twig, app/Resources/views/admission_admin/application.html.twig, app/Resources/views/team/team_page.html.twig, src/AppBundle/Entity/Application.php, src/AppBundle/Form/Type/ApplicationExistingUserType.php, src/AppBundle/Form/Type/ApplicationPracticalType.php, src/AppBundle/Tests/Controller/AdmissionControllerTest.php
=> Existing application

app/Resources/views/team/application_email.html.twig, app/Resources/views/team/team_application.html.twig, app/Resources/views/team_admin/show_application.html.twig
=> changed the order of 'motivasjon' and 'om deg selv'

app/Resources/views/reset_password/new_password_email.txt.twig, src/AppBundle/Controller/PasswordResetController.php
Inaktive brukere burde ikke kunne be om å resette passordet sitt.
=> Disable password reset feature for inactive users

app/Resources/views/admission/application_form.html.twig, app/Resources/views/assistant/assistants.html.twig, src/AppBundle/Controller/AssistantController.php, src/AppBundle/EventSubscriber/ApplicationSubscriber.php
Jeg løste dette ved å sende en liste med formviews fra controlleren, én for hver department. 
Lager PR så vi kan se litt nøyere på det før det merges sammen med resten av redesign-mylderet. Også fordi dette er opptaksformen det er snakk om, og det er ekstra viktig at den funker :sweat_smile:
=> Switch department in admission form without reloading the page

app/Resources/views/semester_admin/create_semester.html.twig, src/AppBundle/Tests/Controller/SemesterControllerTest.php
Ok så det var ikke meningen å pushe resten av branchen til master først. Sorry about that
Evt. kommenter her på tingene jeg allerede pusha til master
=> Fikse litt på semester UIen

app/Resources/assets/js/bankAccountNumberValidation.js
Mod11 algoritmen som brukes til å validere bankkontonummer var broken
=> Fix bank account number validation

app/Resources/assets/js/bankAccountNumberValidation.js
Funker ikke å bruke !== med en int og en string :innocent:
=> Fix mod11 algorithm again

app/DoctrineMigrations/Version20180425134449.php, app/Resources/views/receipt/my_receipts.html.twig, src/AppBundle/Entity/Receipt.php
=> Set receipt description max length to 5000

app/Resources/views/mailing_list/mailinglist_show.html.twig, src/AppBundle/Controller/MailingListController.php, src/AppBundle/Tests/Controller/MailingListControllerTest.php
=> Use company email in mailing lists

src/AppBundle/Controller/AssistantController.php
Siden scrolla ikke ned når det var errors i formen og valgte heller ikke riktig department
=> Scroll to admission form

app/Resources/views/assistant/assistants.html.twig, src/AppBundle/Entity/AdmissionSubscriber.php
=> Fix typo in admission subscriber validation message

app/Resources/views/admission/application_confirmation.html.twig, app/Resources/views/admission/application_form.html.twig, src/AppBundle/Entity/Application.php, src/AppBundle/Resources/config/services.yml, src/AppBundle/Service/ApplicationAdmission.php, src/AppBundle/Tests/Controller/AssistantControllerTest.php, src/AppBundle/Validator/Constraints/ApplicationEmail.php, src/AppBundle/Validator/Constraints/ApplicationEmailValidator.php
=> Validate that the same email can only be used once in application each semester

app/Resources/assets/scss/pages/team.scss, app/Resources/views/contact/index.html.twig, app/Resources/views/profile/contact_info.html.twig, app/Resources/views/team/team_page.html.twig, app/config/security.yml, src/AppBundle/Controller/ProfileController.php, src/AppBundle/Tests/Availability/AvailabilityFunctionalTest.php
#900, #830 
La merke til at det allerede lå styling inne for mail-linkene på team sida. Hvorfor vi bestemte oss for å fjerne dem er uvisst.
=> Make all team member profiles public

app/Resources/views/stand_admin/stand.html.twig, app/config/services.yml, src/AppBundle/Controller/StandController.php, src/AppBundle/Entity/Repository/ApplicationRepository.php, src/AppBundle/Service/AdmissionStatistics.php
=> Show applications graph on stand page

app/Resources/views/home/index.html.twig
=> Use department city instead of shortName in admission banner on home page

app/Resources/assets/scss/pages/assistants.scss, app/Resources/views/assistant/assistants.html.twig, src/AppBundle/Controller/AssistantController.php, src/AppBundle/Service/FilterService.php
Legger til en knapp for å scrolle ned til søknadsskjemaet nederst på assistentsida.
=> Show call to action link on assistant page

app/Resources/views/confirmation/confirmation.html.twig
For å få litt marigin til høyre/venstre slik at teksten ikke strekkes helt ut i kanten på skjermen (på mobil)
=> Add container around confirmation page content

app/DoctrineMigrations/Version20180813134540.php, app/Resources/views/admission_admin/interviewed_applications_table.html.twig, app/Resources/views/certificate/signature_picture_upload.html.twig, src/AppBundle/Controller/UserAdminController.php, src/AppBundle/Entity/Application.php, src/AppBundle/Entity/Article.php, src/AppBundle/Entity/AssistantHistory.php, src/AppBundle/Entity/CertificateRequest.php, src/AppBundle/Entity/ExecutiveBoardMembership.php, src/AppBundle/Entity/Interview.php, src/AppBundle/Entity/InterviewQuestionAlternative.php, src/AppBundle/Entity/Receipt.php, src/AppBundle/Entity/Signature.php
=> Add missing cascade deletes

app/DoctrineMigrations/Version20180813134540.php
Autodeploy sciptet feilet siden det var feil FKs i migration scriptet
=> Fix FKs in migration script

app/DoctrineMigrations/Version20180822200336.php, app/Resources/views/interview/email.html.twig, app/Resources/views/interview/preview.html.twig, app/Resources/views/interview/schedule.html.twig, app/Resources/views/my_page/interview_description.html.twig, app/Resources/views/my_page/interview_info.html.twig, app/Resources/views/my_page/interview_invitation.html.twig, src/AppBundle/Controller/InterviewController.php, src/AppBundle/Entity/Interview.php, src/AppBundle/Form/Type/ScheduleInterviewType.php, src/AppBundle/Service/InterviewManager.php
=> Add campus field to interview schedule form

app/Resources/assets/scss/pages/team.scss, app/Resources/views/team/team_card.html.twig
=> Make link in team cards more fancy

app/Resources/views/team_admin/show_applications.html.twig
=> Don't delete team when "not confirmed" is clicked

app/Resources/views/interview/response.html.twig, src/AppBundle/Controller/InterviewController.php
=> Render application status on interview response page if already responded

app/DoctrineMigrations/Version20180831172454.php, src/AppBundle/Entity/Interview.php, src/AppBundle/Entity/Repository/InterviewRepository.php, src/AppBundle/Service/InterviewManager.php
=> Autofill room, campus and mapLink when scheduling interviews

app/Resources/views/admission_admin/assigned_table.html.twig, app/Resources/views/error/control_panel_error.html.twig, app/Resources/views/interview/assign_co_interview_form.html.twig, app/config/routing.yml, src/AppBundle/Controller/InterviewController.php, src/AppBundle/Service/InterviewManager.php
=> CoInterviewers can conduct assigned interviews

app/Resources/views/about/about_vektor.html.twig
Legg til "Kontakt oss" nederst på siden.
=> Contact text faq

app/DoctrineMigrations/Version20180906230948.php, app/Resources/views/school_admin/index.html.twig, app/Resources/views/school_admin/school_table.html.twig, src/AppBundle/Controller/SchoolAdminController.php, src/AppBundle/DataFixtures/ORM/LoadDepartmentData.php, src/AppBundle/DataFixtures/ORM/LoadSchoolData.php, src/AppBundle/Entity/Repository/SchoolRepository.php, src/AppBundle/Entity/School.php, src/AppBundle/Form/Type/CreateAssistantHistoryType.php, src/AppBundle/Form/Type/CreateSchoolType.php, src/AppBundle/Form/Type/SchoolCapacityType.php, src/AppBundle/Tests/Form/Type/CreateSchoolTest.php
Lar oss gjøre skoler inaktive (#1002)
=> Add active field to school entity

src/AppBundle/Google/GoogleUsers.php
Hent ut bruker direkte i stedet for å lete gjennom alle brukere
=> Update Google GetUser() function

src/AppBundle/Google/GoogleUsers.php, src/AppBundle/Resources/config/services.yml, src/AppBundle/Service/RoleManager.php
=> Suspend G Suite user when demoted to Assistant (unsuspend when promoted to team member)

src/AppBundle/Controller/AdmissionAdminController.php
=> Send mail to applicant created from control panel

app/Resources/views/interview/conduct.html.twig
Det faller mer naturlig enn etter intervjuet i følge flere kilder
=> Move team interest question up in form

src/AppBundle/Service/InterviewManager.php
=> send mail to co interviewer and interviewer

app/AppKernel.php, app/Resources/assets/scss/app.scss, app/Resources/views/contact/contact_form.html.twig, app/Resources/views/contact/index.html.twig, app/config/config.yml, app/config/config_prod.yml, app/config/parameters.yml.dist, composer.json, composer.lock, src/AppBundle/Controller/ContactController.php, src/AppBundle/Form/Type/SupportTicketType.php
=> Add recaptcha to contact form

app/Resources/views/admission/application_page.html.twig, app/Resources/views/stand_admin/stand.html.twig, src/AppBundle/Controller/AssistantController.php
=> Application site

app/Resources/views/receipt_admin/receipts_table_individual.html.twig
=> Show refund date in receipt table

app/Resources/views/admission/application_form.html.twig, app/Resources/views/admission/application_page.html.twig, app/Resources/views/admission_subscriber/subscribe_page.html.twig, app/Resources/views/team_interest/team_interest.html.twig
=> Form autocomplete

app/Resources/views/common/department_dropdown.html.twig
=> show all departments for admins and active for others

src/AppBundle/Controller/AdmissionAdminController.php, src/AppBundle/Controller/AssistantController.php, src/AppBundle/Controller/ExecutiveBoardController.php
=> Action suffix in public controller methods

app/config/event_subscribers.yml, src/AppBundle/EventSubscriber/DbSubscriber.php
=> Fix entity subscriber not sending logs to slack

app/Resources/assets/js/access_control.js
=> Auto hide forms with no access

app/Resources/views/error/no_assistanthistory.html.twig, src/AppBundle/Entity/User.php, tests/AppBundle/Controller/ExistingUserAdmissionControllerTest.php
=> Fix sneaky admissions

src/AppBundle/Controller/InterviewController.php
=> Update conducted timestamp when saving interview

app/Resources/assets/js/button_deactivator.js, app/Resources/assets/scss/app.scss, app/Resources/assets/scss/control_panel.scss, app/Resources/views/interview/schedule.html.twig, app/Resources/views/team_admin/create_team.html.twig
=> Fix issues with button_deactivator

src/AppBundle/EventSubscriber/IntroductionEmailSubscriber.php
=> Change welcome email type to HTML

app/config/services.yml, src/AppBundle/Controller/Api/PartyController.php, src/AppBundle/Entity/Application.php, src/AppBundle/Entity/Repository/ApplicationRepository.php, src/AppBundle/Entity/School.php
```
/api/party/newest_applications/1/
```
De 5 siste søkerne, formatert slik:
```javascript
[
{
"id": 111,
"yearOfStudy": "1. klasse",
"user": {
"firstName": "test",
"lastName": "test",
"fieldOfStudy": {
"name": "Bachelor i informatikk",
"shortName": "BIT"
}
}
},
{
"id": 110,
"yearOfStudy": "1. klasse",
"user": {
"firstName": "Sigurd",
"lastName": "Totland",
"fieldOfStudy": {
"name": "Bachelor i informatikk",
"shortName": "BIT"
}
}
},
{
"id": 5,
"yearOfStudy": "1",
"user": {
"firstName": "Erik",
"lastName": "Trondsen ",
"fieldOfStudy": {
"name": "Bachelor i informatikk",
"shortName": "BIT"
}
}
},
{
"id": 6,
"yearOfStudy": "1",
"user": {
"firstName": "Assistent",
"lastName": "Johansen",
"fieldOfStudy": {
"name": "Bachelor i informatikk",
"shortName": "BIT"
}
}
},
{
"id": 7,
"yearOfStudy": …
```
=> Add endpoint for getting the latest applications

app/AppKernel.php, app/config/config.yml, app/config/security.yml, app/config/services.yml, composer.json, composer.lock, src/AppBundle/Controller/Api/PartyController.php, src/AppBundle/Entity/Application.php, src/AppBundle/Entity/Repository/ApplicationRepository.php, src/AppBundle/Entity/School.php
Denne PRen legger til FOSRestBundle og foreslår patterns for å utvikle RESTfulle endpoints på toppen av  entity-strukturen vi allerede har. Her har jeg _i controlleren_ bestemt akkurat hvordan dataene jeg vil henter ut skal struktureres, istedenfor å definere i enetityene hvilke felter som skal tas med/ignoreres.
=> Implement party API

src/AppBundle/Controller/SurveyController.php, src/AppBundle/Entity/Survey.php, src/AppBundle/Form/Type/SurveyType.php
* Fixes old survey being modified when making a new copy
* Fixes #1174 
* Allows creating surveys for old semesters
=> Survey hotfix

client/src/components/CountDown.vue, client/src/views/partypage/PartyPageView.vue
Sets new countdown time on party page according to this semester. Also hides the assistants last name on popup.
=> Update party page 

client/src/views/partypage/PartyPageView.vue
Change background color palette on party-page.
=> Party-page: Change background colors

app/Resources/assets/scss/control_panel.scss, app/Resources/views/widgets/receipts_widget.html.twig, src/AppBundle/Controller/WidgetController.php
=> Show wholesome message in receipt widget when all receipts are paid

src/AppBundle/Service/CompanyEmailMaker.php, tests/AppBundle/Service/CompanyEmailMakerTest.php
=> Fix company email maker

app/Resources/views/survey/survey_table.html.twig, src/AppBundle/Controller/SurveyController.php
=> Redirect fix

src/AppBundle/Controller/SurveyController.php
Hindre tilgang i API til undersøkelseresultater hvis undersøkelsen er `confidential`
=> Deny access to confidential surveys if not survey_admin

app/config/security.yml, tests/AppBundle/Availability/AvailabilityFunctionalTest.php
Dette kan vi håndtere med access kontroll isteden
=> Let other users than ROLE_ADMIN users access the staging list

app/Resources/views/admission_period_admin/create_admission_period.html.twig, app/Resources/views/admission_period_admin/edit_admission_period.html.twig, app/Resources/views/interview/schedule.html.twig, app/Resources/views/todo_list/create_todo_element.html.twig
=> Datetimepicker fix

app/Resources/views/feedback_admin/feedback_admin_index.html.twig, app/Resources/views/widgets/feedback_widget.html.twig
=> Centered the feedback form

app/Resources/views/admission_period_admin/create_admission_period.html.twig, app/Resources/views/admission_period_admin/edit_admission_period.html.twig, app/Resources/views/interview/schedule.html.twig, app/Resources/views/todo_list/create_todo_element.html.twig
move dayOfWeekStart:1 to options so as to not overwrite the defined options
Closes  #1250
=> Correct use of options on datetimepickers

app/Resources/views/stand_admin/stand.html.twig
=> Fixed a few typos in "stand"

src/AppBundle/Controller/SurveyController.php, src/AppBundle/Service/SurveyManager.php
Check that the answer belongs to the survey in question, not just a question which happens to be in that survey.
Fixes #1251
=> Shows text answers only on the survey result page to the survey they were actually answered on

README.md, package-lock.json, package.json, src/AppBundle/AssistantScheduling/Webapp/package-lock.json
Recently got a new laptop, I had to run npm install node-sass
in order for the dev setup to function properly.
I found version ^4.8.3 in package-lock, so I set that as the version
requirement.
Please just close this PR if it is not necessary 😇
=> Add Node-Sass as a requirement for starting the project

src/AppBundle/Controller/SsoController.php
=> Sjekk om bruker er aktiv i team før de kan logge inn via SSO

app/Resources/views/feedback_admin/feedback_admin_index.html.twig, app/Resources/views/widgets/feedback_widget.html.twig
=> Feedback widget size 

app/Resources/views/base/footer.html.twig, app/Resources/views/base/header.html.twig, app/config/routing.yml
Added "For foreldre" to footer and mobile side-menu.
Also changed /foreldre route name from "foreldre" to "parents"
FIxes #1282
=> Added "For foreldre" to footer and mobile side-menu.

app/Resources/views/changelog/changelog_create.html.twig
Also fixed changelog-cards (Submit button not in own card)
Fixes #1288
=> Fix breadcrumb in changelog_create

app/Resources/views/control_panel/index.html.twig, app/Resources/views/widgets/todo_widget.html.twig, src/AppBundle/Controller/WidgetController.php
fixes #1135 
Ser dette greit ut @MathiasWahl ?
=> Added todo-widget

client/src/components/CountDown.vue
PR updates the date for our PartyPage.
=> Set Date for PartyPage

app/Resources/views/feedback_admin/feedback_admin_list.html.twig
=> Feedback -  Added date column

client/README.md
The instructions are now placed in the `readme` in /client
=> Provide directions for getting updates in /client to production

app/Resources/views/assistant/assistants.html.twig, src/AppBundle/Controller/AssistantController.php, src/AppBundle/Controller/TeamApplicationController.php, src/AppBundle/Service/ApplicationAdmission.php
fixes #1207 
Also secures team applications,  throws NotFoundHttpException if found by direct url after deadline
=> Show error message if no active admission period

app/Resources/views/admission/notification_email.html.twig
Lagt til en paragraf ang. Covid-19 på e-posten som blir utsendt til interesselisten.
=> Add paragraph about Covid-19 to notification email

app/Resources/views/parents/parents.html.twig
Small change for the better (hopefully?)
=> Change misguiding text in /foreldre.

client/src/components/CountDown.vue
Oppdaterer dato for party-page slik at den samvarer med dette semesteret.
=> Update party-page date

src/AppBundle/EventSubscriber/ApplicationSubscriber.php, src/AppBundle/EventSubscriber/InterviewSubscriber.php, src/AppBundle/EventSubscriber/IntroductionEmailSubscriber.php, src/AppBundle/EventSubscriber/TeamApplicationSubscriber.php, src/AppBundle/EventSubscriber/TeamInterestSubscriber.php, src/AppBundle/Google/Gmail.php, src/AppBundle/Mailer/Mailer.php, src/AppBundle/Mailer/MailerInterface.php, src/AppBundle/Service/ApplicationAdmission.php, src/AppBundle/Service/EmailSender.php, src/AppBundle/Service/InterviewManager.php, src/AppBundle/Service/InterviewNotificationManager.php, src/AppBundle/Service/LoginManager.php, src/AppBundle/Service/PasswordManager.php, src/AppBundle/Service/SlackMailer.php, src/AppBundle/Service/SurveyNotifier.php, src/AppBundle/Service/UserRegistration.php
Use of `Environment` instead of the deprecated `Twig_Environment`
+
Use imports for `Swift_Mailer`
=> Fix deprecations + Use of imports for Swit_Mailer

app/AppKernel.php, composer.json, composer.lock, package-lock.json, package.json
Package tfox/mpdf-port-bundle was causing problems when installing project with newer versions of php, due to lack of support. 
Package removed due to not being used (was used with Symfony 2).
Also ran `npm audit fix`, which is why there are quite some changes to some files.
=> Remove unused package + npm audit fix

src/AppBundle/Controller/Api/PartyController.php, src/AppBundle/Google/Gmail.php
=> symfony insight: follow PSR-1 coding standard

deploy.sh
Adds logging to backup part of deploy script
=> add logging to backup part of deploy script

src/AppBundle/Service/GeoLocation.php
Tackles another symfony insight suggestion
Closes #1383
=> remove php super global from GeoLocation.php

src/AppBundle/Twig/Extension/SemesterExtension.php
=> Removed unused import in SemesterExtension.php

src/AppBundle/Entity/Repository/SurveyNotificationRepository.php
Found some unused imports in AccessRuleRepository also. Get rid of these also?
=> Fixes  #1407

src/AppBundle/Service/ApplicationAdmission.php, src/AppBundle/Service/BetaRedirecter.php, src/AppBundle/Service/UserGroupCollectionManager.php
Fixes #1409 (hopefully) Needs testing.
=> Removed unused imports from services.

sonar-project.properties
PR spesifiserer scope for SonarCloud.
=> Set sonarcloud scope for repo

sonar-project.properties
Fjerner migration-mappen og bootstrap fra sonarcloud sine analyser.
=> Exclude migrations and bootstrap from sonarcloud scope

app/Resources/views/interview/email.html.twig, app/Resources/views/stand_admin/stand.html.twig
=> Fixed mistakes in tags in two files.

composer.json
=> Added two lines two require in composer.json

src/AppBundle/Controller/TeamController.php
=> Deleted indexAction()

src/AppBundle/Controller/AdmissionSubscriberController.php, src/AppBundle/Controller/ArticleAdminController.php, src/AppBundle/Controller/InterviewController.php, src/AppBundle/Controller/InterviewSchemaController.php, src/AppBundle/Controller/ProfileController.php, src/AppBundle/Controller/SchoolAdminController.php, src/AppBundle/Controller/SurveyController.php, src/AppBundle/Controller/UserGroupCollectionController.php, src/AppBundle/EventSubscriber/ApplicationSubscriber.php, src/AppBundle/Service/AccessControlService.php, src/AppBundle/Service/AdmissionNotifier.php, src/AppBundle/Service/RoleManager.php, src/AppBundle/Service/SlackMessenger.php, src/AppBundle/Service/UserGroupCollectionManager.php
=> Use imports for exceptions

app/Resources/views/feedback_admin/feedback_admin_show.html.twig
=> Removed unnecessary break-end tag

app/Resources/views/home/index.html.twig
=> Replaced <center> with class="text-center"

src/AppBundle/Form/InterviewNewTimeType.php, src/AppBundle/Form/Type/AssignInterviewType.php, src/AppBundle/Form/Type/CreateSemesterType.php, src/AppBundle/Form/Type/CreateTeamMembershipType.php, src/AppBundle/Form/Type/CreateUserType.php, src/AppBundle/Form/Type/FeedbackType.php, src/AppBundle/Form/Type/ImageGalleryType.php, src/AppBundle/Form/Type/ScheduleInterviewType.php, src/AppBundle/Form/Type/SchoolCapacityType.php
Fixes #1408 . Needs testing. One of the indications in a form in the issue was false.
=> Removed unused imports in forms.

app/Resources/views/team/team_card.html.twig
Endre slik at teksten for et team-card endres etter om det er 0, 1 eller flere medlemmer
Closes #1389
=> Team member count

app/Resources/views/common/datetime_picker.html.twig
=> Changed to norwegian for datetimepicker

src/AppBundle/Entity/Interview.php
=> Removed unecessary returns in Interview

src/AppBundle/Controller/AccessRuleController.php, src/AppBundle/Controller/AdmissionAdminController.php, src/AppBundle/Controller/AdmissionSubscriberController.php, src/AppBundle/Controller/Api/AccountController.php, src/AppBundle/Controller/ArticleAdminController.php, src/AppBundle/Controller/AssistantController.php, src/AppBundle/Controller/CertificateController.php, src/AppBundle/Controller/ClientController.php, src/AppBundle/Controller/ConfirmationController.php, src/AppBundle/Controller/ContactController.php, src/AppBundle/Controller/ExecutiveBoardController.php, src/AppBundle/Controller/ExistingUserAdmissionController.php, src/AppBundle/Controller/InterviewController.php, src/AppBundle/Controller/SponsorsController.php, src/AppBundle/Controller/StandController.php, src/AppBundle/Controller/SurveyController.php, src/AppBundle/Controller/TeamAdminController.php, src/AppBundle/Controller/TeamInterestController.php, src/AppBundle/Controller/UserController.php
=> Fixes deprecated annotations

README.md
La in instruksjoner for å installere dependecies med composer
=> Legger til en litt enklere installasjon for oss med windows

src/AppBundle/DataFixtures/ORM/LoadTodoItemData.php, src/AppBundle/Entity/Repository/SocialEventRepository.php, src/AppBundle/Entity/Survey.php, src/AppBundle/Entity/SurveyTaken.php, src/AppBundle/Entity/TodoItem.php, src/AppBundle/Service/SlugMaker.php, src/AppBundle/Service/SurveyManager.php, src/AppBundle/Service/TodoListService.php, src/AppBundle/Service/UserGroupCollectionManager.php, src/AppBundle/Service/UserRegistration.php
Litt småplukk:
-Fjerner øverflødige paranteser
-Fjerner en ubrukt import
-Fjerner noe kode som er kommentert ut
-Returnerer noen verdier direkte fremfor å deklarere en variabel som deretter blir returnert
=> Kodeforbedringer

app/config/security.yml
=> Set Firewall provider to chain_provider

.travis.yml
Update php and node versions that travis uses for CI.
=> Update versions in travis.yml

composer.json, composer.lock
This reverts commit 2ad335b16e8e6ec1813c6ae9f6ed0c81345baa56.
=> Revert "Update packages (#1513)"

composer.lock
Due to security issues, symfony package should be updated to 3.4.49
=> Update symfony to 3.4.49

app/Resources/views/certificate/certificate.html.twig, composer.json, composer.lock, deploy.sh, src/AppBundle/Controller/ProfileController.php
=> [VB-40] Fix certificate functionality

app/Resources/views/team/board_and_team.html.twig
Updates the current photo of the executive board 📸
=> [VF-61] Update HS photo

app/Resources/views/base/footer.html.twig
Removes Oslo from footer due to the department no longer being operational :(
=> [VF-62] Remove Oslo from footer

app/Resources/assets/images/slab.svg, app/Resources/views/base/admin/main_navigation.html.twig
Added link in control panel main navigation that opens Slab in the same tab.
Currently in color as its functionality differs from the other links, and to make users aware of its existence 🆘
=> [VB-188] Add slab link to main navigation

app/Resources/views/base/footer.html.twig, app/Resources/views/certificate/certificate.html.twig, src/AppBundle/DataFixtures/ORM/LoadDepartmentData.php
Changed the address from Høgskoleringen 1 to Sem Sælands vei 1.
=> Changed the address
