app/Resources/views/participant_history/index.html.twig
app/Resources/views/profile/profile.html.twig
app/Resources/views/profile/public_profile.html.twig
app/Resources/views/team_admin/create_work_history.html.twig
app/Resources/views/team_admin/specific_team.html.twig
src/AppBundle/Entity/WorkHistory.php
src/AppBundle/Form/Type/CreateWorkHistoryType.php

Når brukere legges til et team velger man startsemester og sluttsemester isteden for startdato og sluttdato.
På profilene vises assistent- og teamhistorikk i tabeller med start- og sluttsemester.
startDate og endDate er erstattet med startSemester og endSemester i WorkHistory entitien.
Databaseskjemaet må derfor oppdateres.

Work History semesters instead of dates

---

app/config/routing.yml
app/config/security.yml

Lagt til /updatestaticcontent i security.yml med krav om å være super admin.
Kun godta POST fra /updatestaticcontent.

Update static content security

---

src/AppBundle/Entity/Repository/ApplicationRepository.php

I PHP 7.0 er ikke `null` en gyldig return type.
Vi kan begynne å bruke nullable return types når vi oppgraderer til versjon 7.1: http://php.net/manual/en/migration71.new-features.php

Allow application repository function to return null

---

src/AppBundle/Tests/BaseWebTestCase.php
src/AppBundle/Tests/Controller/AboutVektorControllerTest.php

I tester er det vanlig å opprette en `Client` og gå til en path:
```php
$client = static::createClient();
$crawler = $client->request('GET', '/omvektor');
$this->assertTrue($client->getResponse()->isSuccessful());
```
I tester som extender `BaseWebTestCase` kan dette kan nå skrives som:
(Nytt i denne PRen)
```php
$crawler = $this->goTo('/omvektor'); // Ikke-innlogget client
```
Dette er ekvivalent med:
(Eksisterer fra før)
```php
$crawler = $this->anonymousGoTo('/omvektor'); // Ikke-innlogget client
```
Klienter med andre rettigheter:
(Eksisterer fra før)
```php
$crawler = $this->assistantGoTo('/omvektor');  // ROLE_USER
$crawler = $this->teamMemberGoTo('/omvektor'); // ROLE_ADMIN
$crawler = $this->teamLeaderGoTo('/omvektor'); // ROLE_SUPER_ADMIN
$crawler = $this->adminGoTo('/omvektor'); …
```

Use anonymousClient as default client in the goTo function

---

app/Resources/views/profile/public_profile.html.twig
src/AppBundle/Controller/ProfileController.php
src/AppBundle/Resources/config/services.yml
src/AppBundle/Service/RoleManager.php
src/AppBundle/Twig/Extension/RoleExtension.php

Issue #461 
Tidligere kunne teamleaders endre rettighetsnivået til admins fra profilsiden. Dette er nå fikset, både i twig og i controlleren. 
Det er også lagt til en `userIsGranted` funksjon til `RoleManager.php` som tar inn en bruker og en rolle. Tilhørende twig-funksjoner er også lagt til i `RoleExtension.php`

Teamleaders should not be able to change the role of admins.

---

app/Resources/views/admission_admin/assigned_table.html.twig
app/Resources/views/interview/schedule.html.twig

Linje og år tar mye plass i tabellen (fordelt), men gir lite verdi.
Hvis man vil vite hvilken linje/år søkere er på kan man gå inn på profilen til brukeren, "sett opp" intervju eller på selve intervjusiden.
Og fjerne "Tidligere deltagelse" fra "sett opp intervju"-siden. De som har deltatt tidligere skal ikke på intervju.

Remove field of study and study year from assigned table

---

src/AppBundle/AssistantScheduling/Webapp/src/Schedule.js

Det hendte at noen assistenter med `doublePosition` og god score ble fordelt til én bolk, men vi kunne oppnådd en bedre total score hvis disse assistentene fikk dobbel stilling.
**Bolk 1**
Assistent A - 20 poeng - Dobbel stilling
Assistent B - 15 poeng - Enkel stilling
**Bolk 2**
Assistent C - 16 poeng - Enkel stilling
Assistent D - 15 poeng - Enkel stilling
**Bolk 1**
Assistent A - 20 poeng - Dobbel stilling
Assistent B - 15 poeng - Enkel stilling
**Bolk 2**
Assistent C - 16 poeng - Enkel stilling
Assistent A - 20 poeng - Dobbel stilling

Scheduling: Improve score optimizer

---

app/Resources/views/profile/public_profile.html.twig

Rolleoppdatering skjer nå helautomatisk. Hvis man endrer en rolle manuelt vil den bli overskrevet neste time, så det er ikke noe poeng å vise denne dropdownen lengre.

Hide role updater for non-admins

---

app/Resources/assets/scss/partials/_typography.scss
app/Resources/views/receipt/create_receipt.html.twig
app/Resources/views/receipt/my_receipts.html.twig
src/AppBundle/Form/Type/AccountNumberType.php

For å gjøre det tydeligere at kontonummeret hører til brukeren, ikke til en enkelt kvittering.
Fixes #664

Update account number label on receipt form

---

app/Resources/views/admission/existingUser.html.twig
src/AppBundle/Controller/AdmissionController.php

Endret label i søknad for tidligere assistenter:
`Legg til personen i teaminteresse-listen?` -> `Kunne du tenke deg å jobbe med organiseringen av Vektorprogrammet? Dette innebærer et verv i et at Vektorprogrammets team`

Update teamInterest label on existing assistant application form

---

src/AppBundle/Tests/Service/SorterTest.php

Denne testen feiltet hvis det tok noen mikrosekunder mellom mock receipt ble opprettet og testen ble kjørt. Tester derfor heller at det er mindre enn 1 sekund mellom tidspunktene enn å teste at de er helt like.

Fix failing receipt sorting test

---

package.json

Gjør at CodeStyle kjører før hver commit, så slipper vi å glemme `npm run cs`

Add code style to pre-commit hook

---

app/DoctrineMigrations/Version20180125205543.php
app/Resources/assets/scss/app.scss
app/Resources/views/admission/admission_existing_email.html.twig
app/Resources/views/admission/existingUser.html.twig
app/Resources/views/admission_admin/application.html.twig
app/Resources/views/form/components/days_checkbox.html.twig
app/Resources/views/interview/conduct.html.twig
app/Resources/views/interview/interview_summary_email.html.twig
app/Resources/views/interview/show.html.twig
app/Resources/views/substitute/index.html.twig
app/Resources/views/substitute/modify_substitute.twig
src/AppBundle/AssistantScheduling/Webapp/src/App.vue
src/AppBundle/Controller/AssistantSchedulingController.php
src/AppBundle/Controller/InterviewController.php
src/AppBundle/DataFixtures/ORM/LoadApplicationData.php
src/AppBundle/Entity/Application.php
src/AppBundle/Entity/Interview.php
src/AppBundle/Form/Type/DaysType.php
src/AppBundle/Tests/Controller/AdmissionControllerTest.php
src/AppBundle/Tests/Controller/InterviewControllerTest.php

resolves #601 
Hver $dag i søknaden har blitt endret fra string til boolean.
True: Dagen passer
False: Dagen passer ikke
I den praktiske delen av intervjuet formulerer vi spørsmålet slik: "Hvilke dager passer IKKE?"
Derfor huker man av hvilke dager som ikke passer. Denne delen av skjemaet mappes tilbake til søknaden på denne måten:
Checkboks valgt: $dag = false
Checkboks ikke valgt: $dag = true

Simplify interview availability question

---

package.json

Ved å legge til `0.0.0.0:8000` i startscriptet kan man nå åpne dev-siden med andre iper enn `127.0.0.1`. F.eks hvis man vil åpne den på mobil.

Run dev server on any ip

---

app/Resources/views/base/admin/footer.html.twig
app/Resources/views/base/admin/main_navigation.html.twig
app/Resources/views/base/admin/mobile_navigation.html.twig
app/Resources/views/control_panel/index.html.twig

- Flyttet *Artikkel* lenger ned på siden, fordi det brukes så sjeldent.
- Flyttet også *Opptaksperiode* til undermenyen *Opptak og undersøkelse*, der den hører bedre hjemme
- Flyttet *Nyhetsbrev* fra *Opptak og undersøkelse* til diverse

Flytte litt på menyene i kontrollpanelet

---

src/AppBundle/Service/AdmissionNotifier.php

Listen med admission subscribers kommer til å vokse fort (flere hundre hvert år), noe som kan skape litt trøbbel mtp. sending limits fra gsuite. Ved å sette en grense for når en subscription blir "utdatert" (f.eks. 1 år) begrenses antallet i listen som skal motta e-post. Ved å sette grensen til 1 år vil en subscriber få en notification de neste 2 opptaksperiodene.
Er det nyttig for subsribers å fortsatt motta notifications etter 1 år? Er det sannsynlig at de kommer til å søke som assistent etter 1 år hvis de ikke allerede gjorde det i løpet av de 2 første opptaksperiodene?

Only send admission notifications if subscribed less than one year ago

---

composer.json
composer.lock

Oppdaterer symfony til `2.8.44` pga [https://symfony.com/blog/cve-2018-14773-remove-support-for-legacy-and-risky-http-headers](https://symfony.com/blog/cve-2018-14773-remove-support-for-legacy-and-risky-http-headers)

Update symfony to version 2.8.44

---

app/Resources/views/assistant/assistants.html.twig
src/AppBundle/Controller/AssistantController.php

Selv om department ikke var gitt for `/opptak` og lignende, settes jo `specific_department` til den nærmest brukerens lokasjon. Med denne PRen fungerer det som det skal, altså at `/opptak` og `/assistenter` viser denne CTAen:
i mens `/opptak/Trondheim` og lignende viser denne:

Don't show specific department in CTA if it's determined by geolocation

---

app/Resources/views/my_page/my_page.html.twig
src/AppBundle/Service/ApplicationManager.php

Brukere som har vært assistent tidligere skal ikke intervjues på nytt. Status på søknaden vil derfor gå direkte til:

Update application status for existing assistants

---

app/config/security.yml

Å gå til /profil/partnere krever at brukeren er logget inn ellers vil 
```
if (!$this->getUser()->isActive()) {
throw $this->createAccessDeniedException();
}
```
gi en error.

Ensure user is logged in before accessing /profil/partnere

---

src/AppBundle/Google/GoogleDrive.php

Fixes #1078 
Tidligere har vi satt teamet til å bli 'owner' av team-driven sin for å gi medlemmene mulighet til å slette filer. Nå har det kommet en ny rolle som heter `fileOrganizer` som gir medlemmene mulighet til å legge filer i papirkurven (men ikke slette permanent). 
Samtidig som denne nye rollen har blitt introdusert ser det ut til at det nå kreves at vi sender med et ekstra felt, `'transferOwnership' => 'true'`, nå man overfører eierskap. Dette fører til at vi får feilmelding når vi prøver å gjøre teamet til 'owner', siden vi ikke har med `transferOwnership`-feltet.
Forslag er derfor å gi teamene 'fileOrganizer'-rolle i stedet for 'owner'.

Set drive permission of teams to 'fileOrganizer' instead of 'owner'

---

app/config/config.yml
app/config/services.yml
src/AppBundle/Service/AdmissionNotifier.php

* Send max 100 admission notifications at a time
* Flush DB after each notification is sent to ensure notifications are never sent twice
* Refactor send logic into separate function for simplicity

Nerf admission notifications

---

deploy.sh
gulpfile.js

> ### :heavy_check_mark: Fikser at staging ikke bygger client skikkelig
> ### :question: Fikser error under byggingen av client i prod deploy
I staging er flagget `NODE_ENV` satt til `staging`. I prod derimot er ikke dette flagget satt. Dermed bygges det statiske filer for ment for dev. Eksempel:
Når `NODE_ENV` er `production` eller `staging` bygges en enkel `app.js`.

Build client with production config

---

app/Resources/views/receipt/create_receipt.html.twig

Dette gjøres for å forhindre at folk runder opp eller ned i utleggene, som skaper krøll i budsjettet. (Det må stemme på øret)

Add comment saying the receipt sum must match the outlay sum

---

app/Resources/views/team_admin/welcome_team_membership_mail.html.twig

Det er ingen som skjønner at de skal bruke samme login-info i gsuite og på vektorprogrammet.no, så her er et forsøk på å tydeliggjøre dette i velkomstmailen.

Spesifiser hvilke brukernavn/passord nye teammedlemmer skal logge inn med

---

src/AppBundle/Google/GoogleGroups.php

The current group names are somewhat confusing on the google admin page. This states clearly which department the group comes from.

Add department to group names on google admin

---

app/Resources/views/admission/info_meeting_email.html.twig

Det kom inn noen forespørsler om å fikse på infomøte varselet nå i siste liten. De ville ha inn en link til opptaket. Flyttet også beskrivelsen ovenfor link til fb da dette så mer naturlig ut.
`department` sendes allerede inn som parameter i det templaten renderes, så derfor er ingenting endret der.

Add a link to admission page and move description up in infomeeting mail

---

app/Resources/views/widgets/changelog_widget.html.twig

Also add declarative text
Closes #1259

correct github link on changelog items

---

src/AppBundle/DataFixtures/ORM/LoadChangeLogData.php

Shortened changelogItem's title to under 40 char.
fixes #1274

Fix changelog fixture

---

src/AppBundle/Controller/SsoController.php

Previously, the login checked only team memberships. This caused issues for the members of the executive board, because these memberships are not like those for teams, but rather their own entities.

change method used to check for active membership on sso login

---

app/Resources/views/admission_subscriber/subscribe_page.html.twig
src/AppBundle/Form/Type/AdmissionSubscriberType.php

Also removes form items from twig, and puts the submit button into `AdmissionSubscriberType.php`
Fixes #1291

Remove autocomplete from admission subscriber form

---

src/AppBundle/Form/Type/ApplicationPracticalType.php

Also removed the data parameter to stop it from overwriting data from
old interview. By doing this, the desired effect ('Norsk' by default) is
achieved while still not overwriting if the previous answer was 'Engelsk'
or 'Norsk og engelsk'
Closes #1297

Change language choice from radio buttons to dropdown

---

app/DoctrineMigrations/Version20200406083959.php
app/Resources/views/certificate/certificate.html.twig
app/Resources/views/certificate/index.html.twig
src/AppBundle/Controller/CertificateController.php
src/AppBundle/Controller/ProfileController.php
src/AppBundle/Entity/Signature.php
src/AppBundle/Form/Type/CreateSignatureType.php

In these corona riddled times, there has been expressed wishes to be able to add a custom comment on the certificates generated to the assistants. We wish to be able to inform of any extra ordinary situations that might have had an impact on a given assistant's history.
The Signature entity was used to house an additional_comment field that an administrative user can write and update when generating and downloading the certificates.

Additional comment on certificates

---

app/Resources/views/admission/notification_email.html.twig

Siden e-postene til interesselisten er blitt utsendt, trengs ikke setningene om Covid-19.

Revert "Add paragraph about Covid-19 to notification email"

---

.travis.yml

Travis bruker per nå nodejs 8, mens vi i prod bruker versjon 10. Her burde samme versjon brukes begge stedene.
I prod:

Update travis to use node_js v10 (same as prod)

---

app/Resources/views/receipt/create_receipt.html.twig

Økonomi-teamet ønsker en oppdatert help-text ved utlegg, da flere misforstår og skriver feil beløp.

Update refund help text

---

src/AppBundle/Entity/AdmissionPeriod.php
src/AppBundle/Entity/PeriodInterface.php

When trying to create a new admission period, it would result in an error.
This was because it tried to fill in the Start and End dates for the provided AdmissionPeriod in the form.
The getters did not allow for null returns, but the newly generated AdmissionPeriod object had no data for these fields.
This fix took the approach to allow the getters to return null.
Another approach would be to set default values for the generated admission period.
I thought this solution was a bit more elegant, but 🤷‍♂️

make getters for start/end date for admission period able to return null

---

.travis.yml

Composer versjon 2 er kommet, men vi kjører ikke dette i prod. Denne PRen påser at travis samsvarer med prod.

Ensure that travis doesn't self-update composer

---

web/app.php
web/app_dev.php
web/app_staging.php

Metoden `loadClassCache` er deprecated og fjernes i Symfony 4.0. 
Se [`https://symfony.com/blog/new-in-symfony-3-3-deprecated-the-classloader-component`](https://symfony.com/blog/new-in-symfony-3-3-deprecated-the-classloader-component)
Metoden ble brukt for php versjoner lavere enn 7, og har derfor ikke noe nytte for oss (og derfor deprecated).

Remove deprecated method loadClassCache

---

app/config/config.yml
app/config/services.yml
src/AppBundle/Controller/ArticleAdminController.php

This PR fixes some more deprecations.
- It declares all services to be public in `services.yml`.
This sorts out the two following deprecations:
-- 
- PR adds `SlackSms` as a service in `services.yml`, and enables auto-wiring for it. This solves this deprecation:
--
- PR also sets `container.dumper.inline_class_loader: true` in `config.yml`.
--
- PR removes `trusted_proxies` from `config.yml`, which fixes this deprecation:
-----
Closes #1400,  #1403

Deprecations

---

src/AppBundle/Controller/Api/ReactIntroApiController.php

API that can be used in React intro course.
This API exposes nothing, and returns only a list of quotes to be displayed.
This is created merely as a novelty to be able to fetch data from Vektorprogrammets backend in the course, and will be removed after.

add test api for react intro course

---

app/Resources/views/receipt/create_receipt.html.twig
src/AppBundle/Form/Type/ReceiptType.php

We have received complaints regarding the refund form. This suggested change in wording is meant to make the form clearer.

Change wording in refund form
